# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on: 
  push:
    tags:
    - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    
    - name: Execute Gradle build
      run: ./gradlew build
      
    - name: Creates a Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
